services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: anujchess12
      POSTGRES_USER: amitansupriyadarsan
      POSTGRES_DB: my_app_development
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/app
      - ./config/database.yml:/app/config/database.yml
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://amitansupriyadarsan:anujchess12@db:5432/my_app_development

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ./config/database.yml:/app/config/database.yml
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://amitansupriyadarsan:anujchess12@db:5432/my_app_development

volumes:
  postgres_data: